<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Resources\Arrow.cur" />
      <Resource Include="Resources\Arrow.cur" />
      <None Remove="Resources\app.ico" />
      <Resource Include="Resources\app.ico" />
      <Page Remove="Resources\Theme.xaml" />
      <Page Update="View\AddProduct.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\GunsList.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\LogIn.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\ProductWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\Register.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Update="View\UserMenu.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <Page Remove="Resources\LightTheme.xaml" />
      <Resource Include="Resources\LightTheme.xaml" />
      <Page Remove="Resources\DarkTheme.xaml" />
      <Resource Include="Resources\DarkTheme.xaml" />
      <Compile Remove="Resources\Controls.cs" />
    </ItemGroup>

</Project>
