<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DAL_Celebrity\DAL_Celebrity.csproj" />
      <ProjectReference Include="..\DAL_Celebrity_MYSQL\DAL_Celebrity_MYSQL.csproj" />
    </ItemGroup>

</Project>
